CREATE DATABASE ASSESMENT ;
USE ASSESMENT;
CREATE TABLE SALESMAN(
 SALESMANN_ID INT PRIMARY KEY ,
 NAME VARCHAR(45),
 CITY VARCHAR(45),
 COMMISSION INT 
);
SELECT * FROM SALESMAN;
CREATE TABLE CUSTOMER (
   CUSTOMER_ID INT PRIMARY KEY,
   CUST_NAME VARCHAR(45),
   CITY VARCHAR(45),
   GRADE VARCHAR(45) ,
   SALESMAN_ID INT,
   FOREIGN KEY (SALESMAN_ID) references SALESMAN(SALESMANN_ID)
);
SELECT * FROM CUSTOMER;
SELECT
    CUSTOMER.cust_name AS Customer_Name,
    CUSTOMER.city AS Customer_City,
    SALESMAN.name AS Salesman_Name,
    SALESMAN.commission
FROM
    Customer 
INNER JOIN
    Salesman  ON CUSTOMER.salesman_id = SALESMAN.salesmann_id;
    
    
    
